apiVersion: v1
kind: ServiceAccount
metadata:
  name: ratings-service-account
  namespace: test_base_ns
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-deployment
  namespace: test_base_ns
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: ratings
  replicas: 2
  template:
    metadata:
      labels:
        app: ratings
    spec:
      serviceAccountName: ratings-service-account
      containers:
      - name: ratings
        image: iad.ocir.io/idmaqhrbiuyo/ratings-ms:v0.1
        ports:
        - containerPort: 3002
        readinessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2   
        resources:
          limits:
            cpu: "256m" 
            memory: "512Mi"
          requests:
            cpu: "256m"
            memory: "512Mi"


--- 

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ratings-deployment-hpa
  namespace: test_base_ns
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource: 
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization  
          averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ratings-deployment

